# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f25af3c22e341b10b988725dbde52aeb9a17c18ec7c29dd8ab802ba91c965f8920cf0077f06c6a3509c94f988eaba98abda084e0fcc93e9982782b4aea9981f2

test:
  secret_key_base: 2d3dcc3eebf2eda165911e904c2e35d7337ef3f7fd21c7db20e340a7f3090746172d136134db9074a2c31d4b75148bd59de53b92fc7e65b2d255135f8ba10f71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
